//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ButtonAll {
            get {
                return ResourceManager.GetString("ButtonAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clos&amp;e.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Visual S&amp;tyles.
        /// </summary>
        internal static string ButtonDisableThemes {
            get {
                return ResourceManager.GetString("ButtonDisableThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Visual S&amp;tyles.
        /// </summary>
        internal static string ButtonEnableThemes {
            get {
                return ResourceManager.GetString("ButtonEnableThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No To All.
        /// </summary>
        internal static string ButtonNoAll {
            get {
                return ResourceManager.GetString("ButtonNoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes To All.
        /// </summary>
        internal static string ButtonYesAll {
            get {
                return ResourceManager.GetString("ButtonYesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPS.
        /// </summary>
        internal static string CaptionCapsLock {
            get {
                return ResourceManager.GetString("CaptionCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Code.
        /// </summary>
        internal static string CaptionCodeForm {
            get {
                return ResourceManager.GetString("CaptionCodeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string CaptionExport {
            get {
                return ResourceManager.GetString("CaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CaptionHelp {
            get {
                return ResourceManager.GetString("CaptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string CaptionInsert {
            get {
                return ResourceManager.GetString("CaptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUM.
        /// </summary>
        internal static string CaptionNumLock {
            get {
                return ResourceManager.GetString("CaptionNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        internal static string CaptionOverWrite {
            get {
                return ResourceManager.GetString("CaptionOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Output.
        /// </summary>
        internal static string CaptionPrintOutput {
            get {
                return ResourceManager.GetString("CaptionPrintOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRL.
        /// </summary>
        internal static string CaptionScrollLock {
            get {
                return ResourceManager.GetString("CaptionScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string CaptionUpdateCheck {
            get {
                return ResourceManager.GetString("CaptionUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test application for testing the MessageForm class..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Caption.
        /// </summary>
        internal static string DummyCaption {
            get {
                return ResourceManager.GetString("DummyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        internal static string DummyText {
            get {
                return ResourceManager.GetString("DummyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons index multiple entry..
        /// </summary>
        internal static string ExceptionMessageB {
            get {
                return ResourceManager.GetString("ExceptionMessageB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption multiple entry..
        /// </summary>
        internal static string ExceptionMessageC {
            get {
                return ResourceManager.GetString("ExceptionMessageC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default button index multiple entry..
        /// </summary>
        internal static string ExceptionMessageD {
            get {
                return ResourceManager.GetString("ExceptionMessageD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon index multiple entry..
        /// </summary>
        internal static string ExceptionMessageI {
            get {
                return ResourceManager.GetString("ExceptionMessageI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments mismatch..
        /// </summary>
        internal static string ExceptionMessageM {
            get {
                return ResourceManager.GetString("ExceptionMessageM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file path multiple entry..
        /// </summary>
        internal static string ExceptionMessageO {
            get {
                return ResourceManager.GetString("ExceptionMessageO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text must be provided..
        /// </summary>
        internal static string ExceptionMessageS {
            get {
                return ResourceManager.GetString("ExceptionMessageS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text multiple entry..
        /// </summary>
        internal static string ExceptionMessageT {
            get {
                return ResourceManager.GetString("ExceptionMessageT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown switch was provided..
        /// </summary>
        internal static string ExceptionMessageU {
            get {
                return ResourceManager.GetString("ExceptionMessageU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message form maximum width multiple entry..
        /// </summary>
        internal static string ExceptionMessageW {
            get {
                return ResourceManager.GetString("ExceptionMessageW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /c\tMessage form caption..
        /// </summary>
        internal static string HelpLine1 {
            get {
                return ResourceManager.GetString("HelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /o\tOutput file full path..
        /// </summary>
        internal static string HelpLine10 {
            get {
                return ResourceManager.GetString("HelpLine10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /T\tArgument parsing test..
        /// </summary>
        internal static string HelpLine11 {
            get {
                return ResourceManager.GetString("HelpLine11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /h or /?\tWill show this help..
        /// </summary>
        internal static string HelpLine12 {
            get {
                return ResourceManager.GetString("HelpLine12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /t\tMessage text..
        /// </summary>
        internal static string HelpLine2 {
            get {
                return ResourceManager.GetString("HelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /b\tButtons index..
        /// </summary>
        internal static string HelpLine3 {
            get {
                return ResourceManager.GetString("HelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /i\tIcon index..
        /// </summary>
        internal static string HelpLine4 {
            get {
                return ResourceManager.GetString("HelpLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /d\tDefault button index..
        /// </summary>
        internal static string HelpLine5 {
            get {
                return ResourceManager.GetString("HelpLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /e\tDisplay help button..
        /// </summary>
        internal static string HelpLine6 {
            get {
                return ResourceManager.GetString("HelpLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /m\tMaximum width in pixels..
        /// </summary>
        internal static string HelpLine7 {
            get {
                return ResourceManager.GetString("HelpLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /w\tNo wrap..
        /// </summary>
        internal static string HelpLine8 {
            get {
                return ResourceManager.GetString("HelpLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /s\tBasic theme..
        /// </summary>
        internal static string HelpLine9 {
            get {
                return ResourceManager.GetString("HelpLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available version:.
        /// </summary>
        internal static string LabelAvailableVersion {
            get {
                return ResourceManager.GetString("LabelAvailableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickedButton:.
        /// </summary>
        internal static string LabelClickedButton {
            get {
                return ResourceManager.GetString("LabelClickedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogResult:.
        /// </summary>
        internal static string LabelDialogResult {
            get {
                return ResourceManager.GetString("LabelDialogResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version:.
        /// </summary>
        internal static string LabelThisVersion {
            get {
                return ResourceManager.GetString("LabelThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string LabelWebsite {
            get {
                return ResourceManager.GetString("LabelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &amp;Reset....
        /// </summary>
        internal static string MenuItemApplicationReset {
            get {
                return ResourceManager.GetString("MenuItemApplicationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for &amp;Updates....
        /// </summary>
        internal static string MenuItemCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuItemCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string MenuItemCopy {
            get {
                return ResourceManager.GetString("MenuItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;About Text.
        /// </summary>
        internal static string MenuItemCopyAbout {
            get {
                return ResourceManager.GetString("MenuItemCopyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Link.
        /// </summary>
        internal static string MenuItemCopyLink {
            get {
                return ResourceManager.GetString("MenuItemCopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Version.
        /// </summary>
        internal static string MenuItemCopyVersion {
            get {
                return ResourceManager.GetString("MenuItemCopyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable &amp;Themes.
        /// </summary>
        internal static string MenuItemDisableThemes {
            get {
                return ResourceManager.GetString("MenuItemDisableThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t &amp;Word Wrap.
        /// </summary>
        internal static string MenuItemDontWordWrap {
            get {
                return ResourceManager.GetString("MenuItemDontWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &amp;Themes.
        /// </summary>
        internal static string MenuItemEnableThemes {
            get {
                return ResourceManager.GetString("MenuItemEnableThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot &amp;Export....
        /// </summary>
        internal static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snapshot Export (Basic Theme)....
        /// </summary>
        internal static string MenuItemExportBasic {
            get {
                return ResourceManager.GetString("MenuItemExportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online &amp;Help.
        /// </summary>
        internal static string MenuItemOnlineHelp {
            get {
                return ResourceManager.GetString("MenuItemOnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MenuItemOptions {
            get {
                return ResourceManager.GetString("MenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preferences....
        /// </summary>
        internal static string MenuItemPreferences {
            get {
                return ResourceManager.GetString("MenuItemPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string MenuItemPrint {
            get {
                return ResourceManager.GetString("MenuItemPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print (&amp;Basic Theme)....
        /// </summary>
        internal static string MenuItemPrintBasic {
            get {
                return ResourceManager.GetString("MenuItemPrintBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view....
        /// </summary>
        internal static string MenuItemPrintPreview {
            get {
                return ResourceManager.GetString("MenuItemPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Previe&amp;w (Basic Theme)....
        /// </summary>
        internal static string MenuItemPrintPreviewBasic {
            get {
                return ResourceManager.GetString("MenuItemPrintPreviewBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string MenuItemSelectAll {
            get {
                return ResourceManager.GetString("MenuItemSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Code....
        /// </summary>
        internal static string MenuItemShowCode {
            get {
                return ResourceManager.GetString("MenuItemShowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Dialog....
        /// </summary>
        internal static string MenuItemShowDialog {
            get {
                return ResourceManager.GetString("MenuItemShowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Word Wrap.
        /// </summary>
        internal static string MenuItemWordWrap {
            get {
                return ResourceManager.GetString("MenuItemWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicacion cannot run on your system..
        /// </summary>
        internal static string MessageApplicationCannotRun {
            get {
                return ResourceManager.GetString("MessageApplicationCannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Application will close now..
        /// </summary>
        internal static string MessageApplicationError {
            get {
                return ResourceManager.GetString("MessageApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string MessageConnecting {
            get {
                return ResourceManager.GetString("MessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export canceled.
        /// </summary>
        internal static string MessageExportCanceled {
            get {
                return ResourceManager.GetString("MessageExportCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed.
        /// </summary>
        internal static string MessageExportFailed {
            get {
                return ResourceManager.GetString("MessageExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export finished.
        /// </summary>
        internal static string MessageExportFinished {
            get {
                return ResourceManager.GetString("MessageExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting….
        /// </summary>
        internal static string MessageExporting {
            get {
                return ResourceManager.GetString("MessageExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating preview....
        /// </summary>
        internal static string MessageGeneratingPreview {
            get {
                return ResourceManager.GetString("MessageGeneratingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help button clicked.
        /// </summary>
        internal static string MessageHelpButtonClicked {
            get {
                return ResourceManager.GetString("MessageHelpButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help requested.
        /// </summary>
        internal static string MessageHelpRequested {
            get {
                return ResourceManager.GetString("MessageHelpRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server response.
        /// </summary>
        internal static string MessageInvalidResponse {
            get {
                return ResourceManager.GetString("MessageInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences saved.
        /// </summary>
        internal static string MessagePreferencesSaved {
            get {
                return ResourceManager.GetString("MessagePreferencesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview generated.
        /// </summary>
        internal static string MessagePreviewGenerated {
            get {
                return ResourceManager.GetString("MessagePreviewGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing....
        /// </summary>
        internal static string MessagePrinting {
            get {
                return ResourceManager.GetString("MessagePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed.
        /// </summary>
        internal static string MessagePrintingFailed {
            get {
                return ResourceManager.GetString("MessagePrintingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing finished.
        /// </summary>
        internal static string MessagePrintingFinished {
            get {
                return ResourceManager.GetString("MessagePrintingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MessageReady {
            get {
                return ResourceManager.GetString("MessageReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset this application to it&apos;s default state?.
        /// </summary>
        internal static string MessageResetWarningLine1 {
            get {
                return ResourceManager.GetString("MessageResetWarningLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings will be lost..
        /// </summary>
        internal static string MessageResetWarningLine2 {
            get {
                return ResourceManager.GetString("MessageResetWarningLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        internal static string MessageUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates. Please try again later..
        /// </summary>
        internal static string MessageUpdateCheckError {
            get {
                return ResourceManager.GetString("MessageUpdateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date..
        /// </summary>
        internal static string MessageUpToDate {
            get {
                return ResourceManager.GetString("MessageUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldError {
            get {
                object obj = ResourceManager.GetObject("ShieldError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldOK {
            get {
                object obj = ResourceManager.GetObject("ShieldOK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestion {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestion", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestionRed {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestionRed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldWarning {
            get {
                object obj = ResourceManager.GetObject("ShieldWarning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit website.
        /// </summary>
        internal static string ToolTipVisit {
            get {
                return ResourceManager.GetString("ToolTipVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fortsoft.eu/.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
